<a href="https://colab.research.google.com/github/Hertoli/HandConnect/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importar NumPy

In [ ]:
import numpy as np


Crear un arreglo de ceros de tamaño 5

In [ ]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

Crear un arreglo de unos de tamaño 10

In [ ]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Crear un arreglo con valores del 10 al 49



In [ ]:
np.arange(10, 50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Crear una matriz identidad de 3x3

In [ ]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Cambiar la forma (reshape) de un arreglo de 1D a 2D




In [ ]:
arr = np.arange(9)
arr.reshape(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Obtener los índices de los elementos distintos de cero

In [ ]:
arr = np.array([1, 0, 2, 0, 3])
np.nonzero(arr)


(array([0, 2, 4]),)

Invertir un arreglo

In [ ]:
arr = np.arange(10)
arr[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Encontrar los valores únicos en un arreglo

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4])
np.unique(arr)


array([1, 2, 3, 4])

Reemplazar todos los valores mayores a 5 por 0

In [ ]:
arr = np.arange(10)
arr[arr > 5] = 0


Sumar dos matrices

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A + B


array([[ 6,  8],
       [10, 12]])

Calcular la media, mediana y desviación estándar de un arreglo

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.mean(arr), np.median(arr), np.std(arr)


(np.float64(3.0), np.float64(3.0), np.float64(1.4142135623730951))

Multiplicar una matriz por un escalar

In [ ]:
A = np.array([[1, 2], [3, 4]])
A * 2


array([[2, 4],
       [6, 8]])

Obtener el producto punto de dos vectores


In [ ]:
v1 = np.array([1, 2])
v2 = np.array([3, 4])
np.dot(v1, v2)


np.int64(11)

Obtener la matriz transpuesta y la inversa

In [ ]:
A = np.array([[1, 2], [3, 4]])
A.T, np.linalg.inv(A)


(array([[1, 3],
        [2, 4]]),
 array([[-2. ,  1. ],
        [ 1.5, -0.5]]))